### ISSUE TITLE
Song map file and version reverted to an archived version of the song map, reset download numbers and file

### ISSUE THREAD

**Issue by rocket52** [Byorun/beatsaver-laravel#40] opened 2018-10-11 20:16 UTC
I had noticed this with my recent song : 
https://beatsaver.com/browse/detail/6586
The updated version is "6586-6219", but the link shows 6586-6216
The downloads reset and the file is now the old link.

From what i've heard in the discord, this isnt the first case.

edit: I think updating the description updated it to the correct version. Or someone on the dev team fixed it quickly :P

**Comment by Razzeee** [comment] 2018-10-11 21:15
Link shows the correct version for me. Maybe the cache got refreshed since you wrote this?

![image](https://user-images.githubusercontent.com/5943908/46834315-f1602f80-cd5f-11e8-9fd8-4da734498082.png)

**Comment by rocket52** [comment] 2018-10-11 21:38
Quite possible. I think it may have been because I edited the deacription, maybe. I looked it up again just now and the number of downloads is refreshed too

**Comment by Byorun** [comment] 2018-10-15 09:34
In some wired circumstances the caching may mess up some things. I close this one since it cannot be reproduced right now.

**Closed by Byorun** 2018-10-15 09:34 UTC
